# Generated by Django 3.2.9 on 2021-12-17 07:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0002_auto_20211217_0759'),
        ('posts', '0002_post_user'),
    ]

    operations = [
    ]
