# Generated by Django 3.2.9 on 2021-12-17 08:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0003_merge_0002_auto_20211217_0759_0002_post_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='user',
            new_name='author',
        ),
    ]
