# Generated by Django 3.2.9 on 2021-12-18 09:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0006_alter_post_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='image',
            field=models.FileField(null=True, upload_to='posts/image/%Y/%m/%d/'),
        ),
        migrations.AlterField(
            model_name='post',
            name='file',
            field=models.FileField(null=True, upload_to='posts/image'),
        ),
    ]
