# Generated by Django 3.2.9 on 2021-12-19 05:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0007_auto_20211218_1024'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='image',
        ),
        migrations.AddField(
            model_name='post',
            name='image_field',
            field=models.ImageField(null=True, upload_to='post/images/%Y/%m/%d/', width_field='image_width'),
        ),
        migrations.AddField(
            model_name='post',
            name='image_width',
            field=models.IntegerField(blank=True, editable=False, null=True),
        ),
    ]
