# Generated by Django 3.2.9 on 2021-12-04 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('publication_year', models.IntegerField()),
                ('author', models.CharField(max_length=255)),
                ('available', models.BooleanField(default=True)),
            ],
        ),
    ]
