# Generated by Django 3.2.9 on 2021-12-18 04:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0004_author'),
    ]

    operations = [
        migrations.AlterField(
            model_name='author',
            name='biogram',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='author',
            name='birth_year',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
